# Test Auth
###
POST http://localhost:8383/api/auth/register
Content-Type: application/json

{
  "email": "test2612@gmail.com",
  "password": "password",
  "firstName": "Dinh",
  "lastName": "Tran"
} 

###
POST http://localhost:8383/api/auth/login
Content-Type: application/json

{
  "email": "test2612@gmail.com",
  "password": "password"
}

# Test User
###
POST http://localhost:8383/api/user/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImlhdCI6MTc1NTQwNDQzMywiZXhwIjoxNzU1NDA4MDMzfQ.h1xl5h10ABMzkA2NuhL9fMclit1H5WaaHvpASNkTofg

{
  "userID": 11,
  "oldPassword": "123456",
  "newPassword": "123456"
}

###
PATCH http://localhost:8383/api/user/updateprofile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTc1NTQwMzk1NCwiZXhwIjoxNzU1NDA3NTU0fQ.XnE3HGDSvWndhuU1jPFOLAqYa5fyYa-KquVELUgKi0s

{
  "firstName": "NewFirstName",
  "lastName": "NewLastName",
  "dateOfBirth": "1999-01-01",
  "gender": "Female"
}

