### TEST GET /api/user/notifications
GET http://localhost:8383/api/user/notifications

### TEST GET /api/user/test
GET http://localhost:8383/api/user/test

### TEST POST /api/user/test
POST http://localhost:8383/api/user/test


###
POST http://localhost:8383/api/auth/login
Content-Type: application/json

{
  "email": "pdinh@gmail.com",
  "password": "testpassword"
}

###
POST http://localhost:8383/api/teams
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzU1MzM4NzgyLCJleHAiOjE3NTUzNDIzODJ9._yuF671OVrEVKopYGy4zMPyKIfy8R34Y7LxXryWl3lc

{
  "id": 8,
  "name": "My Super Cool Team"
}

###
DELETE http://localhost:8383/api/teams/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzU1MzM0NzIxLCJleHAiOjE3NTUzMzgzMjF9.adKJDwOMuyKBFDKq6FqA7TUke3WRQIMkqI3q3jC3zXU

###
PATCH http://localhost:8383/api/teams/6/budget
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzU1MzQyMzk5LCJleHAiOjE3NTUzNDU5OTl9.kHDakprjFe03lrVr7kKJE19QSgN9M7eXGTJdWT-bLYU

{
  "amount": 120
}

###
PATCH http://localhost:8383/api/teams/6/income-goal
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzU1MzQyMzk5LCJleHAiOjE3NTUzNDU5OTl9.kHDakprjFe03lrVr7kKJE19QSgN9M7eXGTJdWT-bLYU

{
  "target": 120
}

###
PATCH http://localhost:8383/api/teams/6/currency
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzU1MzUyNjg0LCJleHAiOjE3NTUzNTYyODR9.MuQMJdSuzg7fvEk6hpGz1sEbqZyXoNDVrh1-OyTrH0Q

{
  "currency": "VND"
}

###
PATCH http://localhost:8383/api/teams/6/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzU1MzUyNjg0LCJleHAiOjE3NTUzNTYyODR9.MuQMJdSuzg7fvEk6hpGz1sEbqZyXoNDVrh1-OyTrH0Q

{
  "name": "Ăn uống",
  "icon": "🍔"
}

###
# Test đổi tên nhóm
PATCH http://localhost:8383/api/teams/6/name
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzU1MzUyNjg0LCJleHAiOjE3NTUzNTYyODR9.MuQMJdSuzg7fvEk6hpGz1sEbqZyXoNDVrh1-OyTrH0Q

{
  "name": "Tên Nhóm Mới Cực Ngầu"
}

###
# Test cho phép thành viên xem báo cáo
PATCH http://localhost:8383/api/teams/6/report-permission
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzU1MzUyNjg0LCJleHAiOjE3NTUzNTYyODR9.MuQMJdSuzg7fvEk6hpGz1sEbqZyXoNDVrh1-OyTrH0Q

{
  "allow": true
}
