### TEST GET /api/user/notifications
GET http://localhost:8383/api/user/notifications

### TEST GET /api/user/test
GET http://localhost:8383/api/user/test

### TEST POST /api/user/test
POST http://localhost:8383/api/user/test


### 
POST http://localhost:8383/api/auth/login
Content-Type: application/json

{
  "email": "pdinh@gmail.com",
  "password": "testpassword"
}


###
POST http://localhost:8383/api/teams
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzU1Njg3MDE0LCJleHAiOjE3NTU2OTA2MTR9.Yd-eVvSzs4qa9v6w3AOczIH8EiLFNiYuo76BtE8O7OU

{
  "id": 11,
  "name": "Test Get Details"
}

###
DELETE http://localhost:8383/api/teams/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzU1MzM0NzIxLCJleHAiOjE3NTUzMzgzMjF9.adKJDwOMuyKBFDKq6FqA7TUke3WRQIMkqI3q3jC3zXU

###
PATCH http://localhost:8383/api/teams/6/budget
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzU1MzQyMzk5LCJleHAiOjE3NTUzNDU5OTl9.kHDakprjFe03lrVr7kKJE19QSgN9M7eXGTJdWT-bLYU

{
  "amount": 120
}

###
PATCH http://localhost:8383/api/teams/6/income-goal
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzU1MzQyMzk5LCJleHAiOjE3NTUzNDU5OTl9.kHDakprjFe03lrVr7kKJE19QSgN9M7eXGTJdWT-bLYU

{
  "target": 120
}

###
PATCH http://localhost:8383/api/teams/6/currency
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzU1MzUyNjg0LCJleHAiOjE3NTUzNTYyODR9.MuQMJdSuzg7fvEk6hpGz1sEbqZyXoNDVrh1-OyTrH0Q

{
  "currency": "VND"
}

###
PATCH http://localhost:8383/api/teams/6/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzU1MzUyNjg0LCJleHAiOjE3NTUzNTYyODR9.MuQMJdSuzg7fvEk6hpGz1sEbqZyXoNDVrh1-OyTrH0Q

{
  "name": "Ăn uống",
  "icon": "🍔"
}

###
# Test đổi tên nhóm
PATCH http://localhost:8383/api/teams/6/name
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzU1MzUyNjg0LCJleHAiOjE3NTUzNTYyODR9.MuQMJdSuzg7fvEk6hpGz1sEbqZyXoNDVrh1-OyTrH0Q

{
  "name": "Tên Nhóm Mới Cực Ngầu"
}

###
# Test cho phép thành viên xem báo cáo
PATCH http://localhost:8383/api/teams/6/report-permission
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzU1MzUyNjg0LCJleHAiOjE3NTUzNTYyODR9.MuQMJdSuzg7fvEk6hpGz1sEbqZyXoNDVrh1-OyTrH0Q

{
  "allow": false
}

###
POST http://localhost:8383/api/teams/13/send-invite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzU1Njg2NjQzLCJleHAiOjE3NTU2OTAyNDN9.tTEYIgX4kGdMlKUDn_1lPnouudVRm-TP5k3UDKh8HZM

{
  "email": "khoi10012005@gmail.com"
}

### Test accept invitation
POST http://localhost:8383/api/teams/1/send-invite/response
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzU1NjgyNTQ1LCJleHAiOjE3NTU2ODYxNDV9.A7-mT4aDHSKDmmcmFjFthYTVpvGs0HBCYiD6LJkTSqc

{
    "inviteToken": "af0e092c-4649-49a7-8055-09e70e83a5de",
    "response": "accept",
    "email": "thai37205@gmail.com"
}

### Test get team details
GET http://localhost:8383/api/teams/13/details
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzU1NzQ2OTM5LCJleHAiOjE3NTU3NTA1Mzl9.jzmRH5H7nmpSI7f9BuquV713RCQubgkF17pFP0W9B1Y

{
  "teamId": 13
}

### test search teams
POST http://localhost:8383/api/user/search-teams
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzU1NzQ2OTM5LCJleHAiOjE3NTU3NTA1Mzl9.jzmRH5H7nmpSI7f9BuquV713RCQubgkF17pFP0W9B1Y

{
  "keyword": "Nhóm"
}