### TEST GET /api/user/notifications
GET http://localhost:8383/api/user/notifications

### TEST GET /api/user/test
GET http://localhost:8383/api/user/test

### TEST POST /api/user/test
POST http://localhost:8383/api/user/test

